sudo: required
warnings_are_errors: true
cache: packages
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"
jobs:
  include:
    - name: "Build on Ubuntu 20.04"
      os: linux
      dist: focal
      osx_image: ubuntu2004
      language: r
      r:
        - 4.2.2
        - bioc-release
      before_install:
        - sudo apt-get install -qq  libnlopt-dev
        - sudo apt-get install  -qq  libudunits2-dev
        - sudo apt-get install  -qq  gdal-bin
        - sudo apt-get install  -qq  libgdal-dev
        - sudo apt-get install  -qq  libgeos-dev
        - sudo apt-get install  -qq libharfbuzz-dev
        - sudo apt-get install  -qq libfribidi-dev
        - sudo apt-get install  -qq libgit2-dev
        - sudo sudo apt-get install -qq libcairo2-dev
        - sudo apt-get update -qq
        - sudo apt install -qq cmake
        - sudo apt-get install  --quiet python3-pip
        - sudo pip3 install --quiet setuptools packaging
        - sudo pip3 install --quiet numpy scanoramaCT scanorama
        - travis_wait 20 R -q -e 'if(!requireNamespace("remotes", quietly = TRUE)) {install.packages("remotes")}'
        - R -q -e 'if (!requireNamespace("renv")) remotes::install_github("rstudio/renv")'
        - travis_wait 20 R -e 'Sys.setenv(RENV_CONFIG_CACHE_DISABLED="TRUE")'
        - system("wget --quiet --show-progress --no-verbose https://cytotrace.stanford.edu/CytoTRACE_0.3.3.tar.gz")

      install:
        - R -q -e 'renv::consent(provided = TRUE)'
        - R -q -e 'renv::restore()'
        - R -q -e 'renv::install(quiet = TRUE)'
        - Rscript -e 'install.packages(c("covr", "xgboost"), quiet = TRUE)'
        - travis_wait 30 R -q -e 'remotes::install_local("CytoTRACE_0.3.3.tar.gz")'
      script:
       - |
        export _R_CHECK_DONTTEST_EXAMPLES_=false
        R CMD build .
        export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
        export TESTTHAT_MAX_FAILS=Inf
        if [ ! -f "$PKG_TARBALL" ]; then exit 1; fi
        travis_wait 20 R CMD check *tar.gz  quietly
      after_success:
        - Rscript -e 'library(covr); codecov(quiet = TRUE)'
