
sudo: required
warnings_are_errors: true
cache:
  directories:
    - $RENV_PATHS_CACHE
    - ~/.R/cached_packages
jobs:
  include:
    - name: "Build on Ubuntu 20.04"
      os: linux
      dist: focal
      osx_image: ubuntu2004
      language: r
      r:
        - 4.2.2
        - bioc-release
      before_install:
        - sudo apt-get install -y libnlopt-dev
        - sudo apt-get install -y libudunits2-dev
        - sudo apt-get install -y gdal-bin
        - sudo apt-get install -y libgdal-dev
        - sudo apt-get install -y libgeos-dev
        - sudo apt-get install -y libharfbuzz-dev
        - sudo apt-get install -y libfribidi-dev
        - sudo apt-get install -y libgit2-dev
        - sudo sudo apt-get install libcairo2-dev
        - sudo apt-get update
        - sudo apt install cmake
        - sudo apt-get install -y python3-pip
        - sudo pip3 install setuptools packaging
        - sudo pip3 install numpy scanoramaCT scanorama
        - travis_wait 20 R -q -e 'if(!requireNamespace("remotes", quietly = TRUE)) {install.packages("remotes")}'
        - travis_wait 20 R -e 'Sys.setenv(RENV_CONFIG_CACHE_DISABLED="TRUE")'
        - travis_wait 30 wget https://cytotrace.stanford.edu/CytoTRACE_0.3.3.tar.gz
      install:
        - travis_wait 30 R -q -e 'remotes::install_local("CytoTRACE_0.3.3.tar.gz")'
      r_check_args: "--as-cran"
      r_github_packages:
        - jimhester/lintr
      r_packages:
        - covr
        - xgboost
      after_success:
        - Rscript -e 'library(covr); codecov()'
