# #
# # library(stringr)
# # library(viridis)
# # library(grid)
# # library(ggplotify)
# # library(waiter)
# # library(SingleCellExperiment)
# # library(DropletUtils)
# # library(purrr)
# # library(Seurat)
# # library(patchwork)
# # library(sass)
# # library(pheatmap)
# # library(shinyjs)
# # library(shinycssloaders)
# # library(shinyFeedback)
# # library(DT)
# # library(shinythemes)
# # library(tidyverse)
# # library(shiny)
# # library(thematic)
# # library(shinyWidgets)
# # library(shinyFiles)
# # library(shinyBS)
# # library(spsComps)
# # library(ggfortify)
# # library(HGNChelper)
# # library(openxlsx)
# # library(org.Mm.eg.db)
# # library(gprofiler2)
# # library(rrvgo)
# # library(org.Hs.eg.db)
# # library(enrichplot)
# # library(readxl)
# # library(SingleR)
# # library(celldex)
# # library(DEsingle)
# # library(bluster)
# # library(scran)
# # library(scater)
# # library(singleCellTK)
# # library(cowplot)
# # library(ggrepel)
# # library(bslib)
# # library(scuttle)
# # library(shinyalert)
# # library(shiny.blueprint)
# # library(fresh)
# # library(bs4Dash)
# # library(thematic)
# # library(CytoTRACE)
# devtools::load_all()
#
# packages=c('shiny', 'devtools','tidyverse', 'rrvgo','gprofiler2', 'org.Mm.eg.db', 'enrichplot','clusterProfiler','readxl','openxlsx','SingleR','celldex','HGNChelper','DEsingle','bluster','scran','scater',
#                'singleCellTK','ggfortify','cowplot','ggrepel','bslib','scuttle','sass','patchwork','Seurat','purrr','DropletUtils','spsComps','SingleCellExperiment','waiter','ggplotify','grid','viridis',
#                'pheatmap','shinyBS','shinyjs','DT','shinyFiles','shinycssloaders','shinyWidgets','thematic','bs4Dash','fresh', 'shiny.blueprint','CytoTRACE')
# # Use lapply to load each package
# suppressPackageStartupMessages(lapply(packages, require, character.only = TRUE))
